baseurl = "https://example.com/" # Include trailing slash
title = "Newsroom"
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = [
  "github.com/onweru/newsroom",
] # edit this if you'ld rather use a fork of this repo
# theme = "newsroom"
author = "Weru"
canonifyurls = true
[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[permalinks]
pages = ':filename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
