baseurl = "https://example.com/"  # Include trailing slash
title = "Newsroom"
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = ["github.com/onweru/newsroom"] # edit this if you'ld rather use a fork of this repo
# theme = "newsroom"
author = "Weru"
canonifyurls = true
paginate = 6

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false # change to true to enable inclusion of rawHTML and math functions
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"

# ids used below are not valid. Replace with valid ones
[params]
  # locale = "en_US"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # mainSections = ["blog", "docs"] see https://gohugo.io/functions/where/#mainsections
  # uncomment the line below will disable darkmode by default.
  # uncomment and set value below to either "light" or "dark" to make default mode dark.
  # defaultMode = "" # Note that the UI control for toggling darkmode will remain in place. This way, the user can decide which mode they would like to use while browsing your website
  logo = "" # if the value is an empty string, the site title will be shown instead
  faviconsDir = "images/icons/" # with a trailing slash
  blogDir = "post" # edit
